### ISSUE TITLE
You can't include the boot ROM in your emulator, it's a copyright violation

### ISSUE THREAD

**Issue by Lokathor** [bkase/gameboy#1]
The boot ROM, in source or binary form, is material owned by Nintendo and protected by copyright. They can cease and desist you or even sue you if you distribute it in your emulator.

The closest you can get is to make the initial emulator state (inclyding all registers and all memory) be whatever you _would have had_ if you really did run the boot ROM at startup.

**Comment by bkase** [comment]
Wow, that’s super annoying! Thank you. I’ll remove it somehow tonight.

**Comment by bkase** [comment]
a048b90 should be good enough for now. I'm hoping I won't get a C&D for the git history (but if it should happen, I'd remake a new repo) 🤷‍♂️

**Comment by Lokathor** [comment]
https://help.github.com/en/articles/removing-files-from-a-repositorys-history

This might do it if you have to. I've never had to scrub a git history myself.
